### ISSUE TITLE
implement .dockerignore

### ISSUE THREAD

**Issue by heph2** [jocker-org/jocker#2]
Actually we're using a Jockerfile `excludes` that takes a list of files/directories to exclude.
It leverage the same stuff that .dockerignore use (`llb.Local` with `llb.LocalOptions`).
But we should also support `.dockerignore` which is a "de facto standard".

Then we need to implement some kind of "prioritization"; if `excludes` exists, then use it, otherwise just use `.dockerignore`.

**Comment by omar-polo** [comment]
closed by mistake
